# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/cpu_project/Nexys-A7-100T-Master.xdc

# IP: ip/blk_mem_gen_4/blk_mem_gen_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_4 || ORIG_REF_NAME==blk_mem_gen_4} -quiet] -quiet

# IP: ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_3 || ORIG_REF_NAME==blk_mem_gen_3} -quiet] -quiet

# IP: ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_2 || ORIG_REF_NAME==blk_mem_gen_2} -quiet] -quiet

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# XDC: d:/cpu_project/Nexys_board_test/Nexys_board_test.gen/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc

# XDC: d:/cpu_project/Nexys_board_test/Nexys_board_test.gen/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc

# XDC: d:/cpu_project/Nexys_board_test/Nexys_board_test.gen/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc

# XDC: d:/cpu_project/Nexys_board_test/Nexys_board_test.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc
