# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/cpu_project/Nexys_board_test/Nexys_board_test.runs/synth_1/main_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/cpu_project/Nexys_board_test/Nexys_board_test.cache/wt [current_project]
set_property parent.project_path D:/cpu_project/Nexys_board_test/Nexys_board_test.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/cpu_project/Nexys_board_test/Nexys_board_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/cpu_project/Nexys_A7_interface/rv32ui-p-add.coe
add_files D:/cpu_project/Nexys_A7_interface/memory_byte_0.coe
add_files D:/cpu_project/Nexys_A7_interface/memory_byte_1.coe
add_files D:/cpu_project/Nexys_A7_interface/memory_byte_2.coe
add_files D:/cpu_project/Nexys_A7_interface/memory_byte_3.coe
add_files D:/cpu_project/Nexys_A7_interface/memory_data.coe
read_mem {
  D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/imports/Nexys_A7_interface/data.mem
  D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/imports/Nexys_A7_interface/rv32ui-p-add.mem
}
read_verilog -library xil_defaultlib {
  D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/imports/Nexys_A7_interface/HEXtoSevenSegment.v
  D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/imports/Nexys_A7_interface/Register_file.v
  D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/imports/Nexys_A7_interface/alu.v
  D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/imports/Nexys_A7_interface/control_unit.v
  D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/imports/Nexys_A7_interface/cpu_top.v
  D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/imports/Nexys_A7_interface/data_mem.v
  D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/imports/Nexys_A7_interface/fsm.v
  D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/imports/Nexys_A7_interface/library.v
  D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/imports/Nexys_A7_interface/program_counter.v
  D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/imports/Nexys_A7_interface/main.v
}
read_ip -quiet D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
set_property used_in_implementation false [get_files -all d:/cpu_project/Nexys_board_test/Nexys_board_test.gen/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc]

read_ip -quiet D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property used_in_implementation false [get_files -all d:/cpu_project/Nexys_board_test/Nexys_board_test.gen/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc]

read_ip -quiet D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all d:/cpu_project/Nexys_board_test/Nexys_board_test.gen/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]

read_ip -quiet D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all d:/cpu_project/Nexys_board_test/Nexys_board_test.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/constrs_1/imports/cpu_project/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/constrs_1/imports/cpu_project/Nexys-A7-100T-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/cpu_project/Nexys_board_test/Nexys_board_test.srcs/utils_1/imports/synth_1/switch.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top main_top -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file main_top_utilization_synth.rpt -pb main_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
